### PR TITLE
tried to fix major scrutinizer issue

### PR DESCRIPTION
**Pull request by mickaelandrieu**
address some issues from scrutinizer in puli/discovery => https://github.com/puli/issues/issues/92

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
hum ... weird. What is the type ``*`` ?

**Comment by webmozart** [comment]
Actually, `bool[][]` is correct.

**Comment by mickaelandrieu** [comment]
Ok, then I don't realy understand the issue from scrutinizer :/

**Comment by webmozart** [comment]
Me neither. I filtered the issue now.

**Pull request closed without merging**
